name: insightmind_app
description: A mental health risk assessment app using Clean Architecture and Riverpod

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^4.0.0
  intl: ^0.20.2
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  table_calendar: ^3.1.2
  fl_chart: ^1.1.1
  flutter_local_notifications: ^19.5.0
  share_plus: ^12.0.1
  timezone: ^0.10.1
  pdf: ^3.11.3
  printing: ^5.14.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^5.12.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true